/* Generated by tools/gen_unicode_tables.py -- Unicode 17.0.0. */
#ifndef U89_PRIV_TABLES_H
#define U89_PRIV_TABLES_H

#include "../include/u89.h"

/* width type: 0 control, 1 zero-width, 2 wide, 3 ambiguous, 4 narrow */
typedef struct u89_priv_wrange { u89_cp lo; u89_cp hi; unsigned char type; } u89_priv_wrange;
extern const u89_priv_wrange u89_priv_width_ranges[];
extern const size_t u89_priv_width_count;

typedef struct u89_priv_range { u89_cp lo; u89_cp hi; } u89_priv_range;
extern const u89_priv_range u89_priv_xid_start_ranges[];
extern const size_t u89_priv_xid_start_count;
extern const u89_priv_range u89_priv_xid_cont_ranges[];
extern const size_t u89_priv_xid_cont_count;
extern const u89_priv_range u89_priv_id_start_ranges[];
extern const size_t u89_priv_id_start_count;
extern const u89_priv_range u89_priv_id_cont_ranges[];
extern const size_t u89_priv_id_cont_count;
extern const u89_priv_range u89_priv_defign_ranges[];
extern const size_t u89_priv_defign_count;
extern const u89_priv_range u89_priv_patws_ranges[];
extern const size_t u89_priv_patws_count;
extern const u89_priv_range u89_priv_patsyn_ranges[];
extern const size_t u89_priv_patsyn_count;
extern const u89_priv_range u89_priv_join_ranges[];
extern const size_t u89_priv_join_count;

typedef struct u89_priv_prop_range { u89_cp lo; u89_cp hi; unsigned short value; } u89_priv_prop_range;
extern const u89_priv_prop_range u89_priv_gc_ranges[];
extern const size_t u89_priv_gc_count;
extern const u89_priv_prop_range u89_priv_gcb_ranges[];
extern const size_t u89_priv_gcb_count;
extern const u89_priv_prop_range u89_priv_incb_ranges[];
extern const size_t u89_priv_incb_count;
extern const u89_priv_prop_range u89_priv_eaw_ranges[];
extern const size_t u89_priv_eaw_count;

extern const u89_priv_range u89_priv_emoji_ranges[];
extern const size_t u89_priv_emoji_count;
extern const u89_priv_range u89_priv_emoji_pres_ranges[];
extern const size_t u89_priv_emoji_pres_count;
extern const u89_priv_range u89_priv_extpict_ranges[];
extern const size_t u89_priv_extpict_count;

typedef struct u89_priv_crange { u89_cp lo; u89_cp hi; unsigned char ccc; } u89_priv_crange;
extern const u89_priv_crange u89_priv_ccc_ranges[];
extern const size_t u89_priv_ccc_count;

typedef struct u89_priv_mapping { u89_cp cp; unsigned long offset; unsigned short length; } u89_priv_mapping;
extern const u89_cp u89_priv_mapping_pool[];
extern const size_t u89_priv_mapping_pool_count;
extern const u89_priv_mapping u89_priv_canon[];
extern const size_t u89_priv_canon_count;
extern const u89_priv_mapping u89_priv_compat[];
extern const size_t u89_priv_compat_count;
extern const u89_priv_mapping u89_priv_casefold_map[];
extern const size_t u89_priv_casefold_map_count;
extern const u89_priv_mapping u89_priv_casefold_turkic_map[];
extern const size_t u89_priv_casefold_turkic_map_count;

typedef struct u89_priv_comp { u89_cp first; u89_cp second; u89_cp result; } u89_priv_comp;
extern const u89_priv_comp u89_priv_comp_tbl[];
extern const size_t u89_priv_comp_count;

#endif
