/* Generated by tools/gen_unicode_tables.py -- Unicode 17.0.0. */
#ifndef UNICODE89_PRIV_TABLES_H
#define UNICODE89_PRIV_TABLES_H

#include "../include/unicode89.h"

/* width type: 0 control, 1 zero-width, 2 wide, 3 ambiguous, 4 narrow */
typedef struct unicode89_priv_wrange { unicode89_cp lo; unicode89_cp hi; unsigned char type; } unicode89_priv_wrange;
extern const unicode89_priv_wrange unicode89_priv_width_ranges[];
extern const size_t unicode89_priv_width_count;

typedef struct unicode89_priv_range { unicode89_cp lo; unicode89_cp hi; } unicode89_priv_range;
extern const unicode89_priv_range unicode89_priv_xid_start_ranges[];
extern const size_t unicode89_priv_xid_start_count;
extern const unicode89_priv_range unicode89_priv_xid_cont_ranges[];
extern const size_t unicode89_priv_xid_cont_count;
extern const unicode89_priv_range unicode89_priv_id_start_ranges[];
extern const size_t unicode89_priv_id_start_count;
extern const unicode89_priv_range unicode89_priv_id_cont_ranges[];
extern const size_t unicode89_priv_id_cont_count;
extern const unicode89_priv_range unicode89_priv_defign_ranges[];
extern const size_t unicode89_priv_defign_count;
extern const unicode89_priv_range unicode89_priv_patws_ranges[];
extern const size_t unicode89_priv_patws_count;
extern const unicode89_priv_range unicode89_priv_patsyn_ranges[];
extern const size_t unicode89_priv_patsyn_count;
extern const unicode89_priv_range unicode89_priv_join_ranges[];
extern const size_t unicode89_priv_join_count;

typedef struct unicode89_priv_prop_range { unicode89_cp lo; unicode89_cp hi; unsigned short value; } unicode89_priv_prop_range;
extern const unicode89_priv_prop_range unicode89_priv_gc_ranges[];
extern const size_t unicode89_priv_gc_count;
extern const unicode89_priv_prop_range unicode89_priv_gcb_ranges[];
extern const size_t unicode89_priv_gcb_count;
extern const unicode89_priv_prop_range unicode89_priv_incb_ranges[];
extern const size_t unicode89_priv_incb_count;
extern const unicode89_priv_prop_range unicode89_priv_eaw_ranges[];
extern const size_t unicode89_priv_eaw_count;

extern const unicode89_priv_range unicode89_priv_emoji_ranges[];
extern const size_t unicode89_priv_emoji_count;
extern const unicode89_priv_range unicode89_priv_emoji_pres_ranges[];
extern const size_t unicode89_priv_emoji_pres_count;
extern const unicode89_priv_range unicode89_priv_extpict_ranges[];
extern const size_t unicode89_priv_extpict_count;

typedef struct unicode89_priv_crange { unicode89_cp lo; unicode89_cp hi; unsigned char ccc; } unicode89_priv_crange;
extern const unicode89_priv_crange unicode89_priv_ccc_ranges[];
extern const size_t unicode89_priv_ccc_count;

typedef struct unicode89_priv_mapping { unicode89_cp cp; unsigned long offset; unsigned short length; } unicode89_priv_mapping;
extern const unicode89_cp unicode89_priv_mapping_pool[];
extern const size_t unicode89_priv_mapping_pool_count;
extern const unicode89_priv_mapping unicode89_priv_canon[];
extern const size_t unicode89_priv_canon_count;
extern const unicode89_priv_mapping unicode89_priv_compat[];
extern const size_t unicode89_priv_compat_count;
extern const unicode89_priv_mapping unicode89_priv_casefold_map[];
extern const size_t unicode89_priv_casefold_map_count;
extern const unicode89_priv_mapping unicode89_priv_casefold_turkic_map[];
extern const size_t unicode89_priv_casefold_turkic_map_count;

typedef struct unicode89_priv_comp { unicode89_cp first; unicode89_cp second; unicode89_cp result; } unicode89_priv_comp;
extern const unicode89_priv_comp unicode89_priv_comp_tbl[];
extern const size_t unicode89_priv_comp_count;

#endif
